### ISSUE TITLE
from_awkward slices sometimes behave as if unpartitioned

### ISSUE THREAD

**Issue by douglasdavis** [ContinuumIO/dask-awkward#27]
Issue to track behavior that surfaced while developing #26

When a dask-awkward Array collection is instantiated via `dak.from_awkward` boolean array selection is broken. This behavior is observed with the threaded scheduler but **not with the distributed scheduler**

reproducer:

```python
import awkward._v2 as ak
import dask_awkward as dak
x = ak.Array([[1, 2, 3], [], [4]])
x = dak.from_awkward(x, npartitions=3)
x_filter = x[x > 2]
x_filter.compute()
```

Traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ddavis/.pyenv/versions/dask-awkward/lib/python3.9/site-packages/dask/base.py", line 288, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/ddavis/.pyenv/versions/dask-awkward/lib/python3.9/site-packages/dask/base.py", line 571, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/ddavis/.pyenv/versions/dask-awkward/lib/python3.9/site-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File "/Users/ddavis/.pyenv/versions/dask-awkward/lib/python3.9/site-packages/dask/local.py", line 507, in get_async
    raise_exception(exc, tb)
  File "/Users/ddavis/.pyenv/versions/dask-awkward/lib/python3.9/site-packages/dask/local.py", line 315, in reraise
    raise exc
  File "/Users/ddavis/.pyenv/versions/dask-awkward/lib/python3.9/site-packages/dask/local.py", line 220, in execute_task
    result = _execute_task(task, data)
  File "/Users/ddavis/.pyenv/versions/dask-awkward/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/ddavis/.pyenv/versions/dask-awkward/lib/python3.9/site-packages/dask/optimization.py", line 969, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/Users/ddavis/.pyenv/versions/dask-awkward/lib/python3.9/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/Users/ddavis/.pyenv/versions/dask-awkward/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/ddavis/.pyenv/versions/dask-awkward/lib/python3.9/site-packages/awkward/_v2/highlevel.py", line 1012, in __getitem__
    out = self._layout[where]
  File "/Users/ddavis/.pyenv/versions/dask-awkward/lib/python3.9/site-packages/awkward/_v2/contents/content.py", line 498, in __getitem__
    return self.__getitem__(where.layout)
  File "/Users/ddavis/.pyenv/versions/dask-awkward/lib/python3.9/site-packages/awkward/_v2/contents/content.py", line 543, in __getitem__
    return self.__getitem__((where,))
  File "/Users/ddavis/.pyenv/versions/dask-awkward/lib/python3.9/site-packages/awkward/_v2/contents/content.py", line 471, in __getitem__
    items = [ak._v2._slicing.prepare_tuple_item(x) for x in where]
  File "/Users/ddavis/.pyenv/versions/dask-awkward/lib/python3.9/site-packages/awkward/_v2/contents/content.py", line 471, in <listcomp>
    items = [ak._v2._slicing.prepare_tuple_item(x) for x in where]
  File "/Users/ddavis/.pyenv/versions/dask-awkward/lib/python3.9/site-packages/awkward/_v2/_slicing.py", line 114, in prepare_tuple_item
    out = prepare_tuple_bool_to_int(prepare_tuple_nested(item))
  File "/Users/ddavis/.pyenv/versions/dask-awkward/lib/python3.9/site-packages/awkward/_v2/_slicing.py", line 304, in prepare_tuple_bool_to_int
    nextcontent = localindex.content.data[item.content.data]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 4
```

**Comment by douglasdavis** [comment]
Not seeing this error anymore, closing for now.
