### ISSUE TITLE
`dak.zip` support for non-`dict` iterables of arrays

### ISSUE THREAD

**Issue by masonproffitt** [ContinuumIO/dask-awkward#77]
For example:

```python
>>> import awkward._v2 as ak
>>> import dask_awkward as dak
>>> aa = ak.Array([[1, 2, 3], [], [2]])
>>> a = dak.from_awkward(aa, npartitions=3)
>>> dak.zip([a, a])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask_awkward/structure.py", line 510, in zip
    raise DaskAwkwardNotImplemented("ak.zip only supports dictionary inputs.")
dask_awkward.utils.DaskAwkwardNotImplemented: ak.zip only supports dictionary inputs.

If you would like this unsupported call to be supported by
dask-awkward please open an issue at:
https://github.com/ContinuumIO/dask-awkward.
```

I assume the error text is a typo (should say `dak.zip`?), since `ak.zip` certainly supports more than just dictionary input:

```python
>>> ak.zip([aa, aa])
<Array [[(1, 1), (2, ...), (3, 3)], ...] type='3 * var * (int64, int64)'>
```

**Comment by douglasdavis** [comment]
Thanks! fixed by https://github.com/ContinuumIO/dask-awkward/commit/105275b1937cce9a80a352af0b200d4e264f27f7

**Comment by douglasdavis** [comment]
Non-dict iterable of arrays is now supported by `dak.zip`.

**Comment by masonproffitt** [comment]
> Non-dict iterable of arrays is now supported by `dak.zip`.

It looks like `list`s are supported but not iterables in general. For example:

```python
>>> dak.zip((a, a))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask_awkward/lib/structure.py", line 568, in zip
    raise DaskAwkwardNotImplemented("dict or list input is supported by dak.zip")
dask_awkward.utils.DaskAwkwardNotImplemented: dict or list input is supported by dak.zip

If you would like this unsupported call to be supported by
dask-awkward please open an issue at:
https://github.com/ContinuumIO/dask-awkward.
```

The exception is also confusing again, since it doesn't say that *only* dict or list input is supported.

**Comment by douglasdavis** [comment]
thanks for catching this, and thanks Jim for the extra info. This is now fixed on `main`
